### ISSUE TITLE
do you have training code for module ?

### ISSUE THREAD

**Issue by rocket1024** [jackhuntcn/facial_beauty_prediction#1]
do you have training code for module ?

**Comment by jackhuntcn** [comment]
yes, in the ipynb file

https://github.com/jackhuntcn/facial_beauty_prediction/blob/master/FBP5500-Resnet50.ipynb

**Comment by rocket1024** [comment]
i see, only single python file ? so can we get correct py file, by using jupyter File—>Download as—>python(.py)? 
or could u commit this file in the git?

**Comment by rocket1024** [comment]
I have exact code,  you use python3 or python2.7?

**Comment by jackhuntcn** [comment]
py2.7

**Comment by rocket1024** [comment]
I am still try py3, got an float convert error, not sure if caused by data corruption, so I download SCUT-FBP5500_v2.1.zip does this same with your SCUT-FBP5500_with_Landmarks.

if not, could u kindly provide your SCUT-FBP5500_with_Landmarks download link? thanks

### 
```
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "FBP5500-Resnet50.py", line 86, in <module>
    [len(x) for x in [lv1,lv2,lv3,lv4,lv5,lv6,lv7,lv8,lv9]])
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 2643, in bar
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 1814, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 2129, in bar
    label='_nolegend_'
  File "/usr/lib/python3/dist-packages/matplotlib/patches.py", line 641, in __init__
    self._x = float(xy[0])
ValueError: could not convert string to float: 'lv1'
```

**Comment by jackhuntcn** [comment]
I can't figure out why is an error here right now, but this part is just plotting a picture to show the distribution of scores in dataset, you can just get rid  of this part in your code.

I downloaded the FBP5500_with_Landmarks dataset from https://github.com/HCIILAB/SCUT-FBP5500-Database-Release

**Comment by rocket1024** [comment]
after comment out the plot, met below issue, after switch to py2.7, same issue exist

```
 /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "FBP5500-Resnet50.py", line 97, in <module>
    x_total = np.empty((nb_samples, img_width, img_height, channels), dtype=np.float32)
MemoryError
```

**Comment by jackhuntcn** [comment]
that means your machine ran out of memory, basically loading all 5500 images (350x350x3) into memory should  consume about 15G RAM. 

you can resize the images to a smaller size like 100*100, or just using a part of this dataset.

**Comment by rocket1024** [comment]
Hi after train I got these npy data, so how we convert into model.h5?
1.6G 5月  31 20:43 x_test.npy
4.9G 5月  31 20:42 x_train.npy
1.3G 5月  31 20:43 x_val.npy
4.5K 5月  31 20:43 y_test.npy
14K 5月  31 20:42 y_train.npy
3.6K 5月  31 20:43 y_val.npy

**Comment by jackhuntcn** [comment]
npy files are just the dataset.

```
filepath="{epoch:02d}-{val_loss:.2f}.h5"
checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
reduce_learning_rate = ReduceLROnPlateau(monitor='loss',
                                         factor=0.1,
                                         patience=2,
                                         cooldown=2,
                                         min_lr=0.00001,
                                         verbose=1)
callback_list = [checkpoint, reduce_learning_rate]
```
the model should be saved in this checkpoint, the file name like '06-0.15.h5', you should check your working directory for the *.h5 file.

**Comment by rocket1024** [comment]
we could get 3 h5 file, but not generate 06-0.15.h5, I could use 05-0.28.h5?

IOError: Unable to open file (unable to open file: name = '06-0.15.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

facial_beauty_prediction$ ls *.h5
01-2.73.h5  02-0.42.h5  05-0.28.h5

**Comment by rocket1024** [comment]
second run generate 06-0.15.h5, thanks

**Comment by yensan0512** [comment]
why the batch size = 16 can't use in training model ?
